
# 使用的 Redis 客户端需要提供 Reactive的操作，目前能够支持的是 Lettuce 和 Redisson，也就是说我们暂时不能使用 Jedis。
spring:
  redis:
      host: 159.75.23.5
      port: 6379
      password: 1234 # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
      database: 0 # Redis 数据库号，默认为 0 。
      timeout: 500 # Redis 连接超时时间，单位：毫秒。
